name: Run linter (selene)
on:
  push:
    branches:
      - main
  pull_request_target:
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate standard library
      run: selene generate-roblox-std
    - name: Run Selene
      run: selene .
